name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2

    - name: Build Cross Compiler
      run: |
        cd ./Scripts/
        sh ./build-cross-compiler.sh
        cd ..

    - name: Build Project Files
      run: |
        cd ./Scripts/  
        sh ./build.sh