name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update environment
        run: |
          sudo apt update -qq
          sudo apt install -y gcc clang gdb build-essential nasm

      - name: Build Project Files
        run: |
          make
          make clean